// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wyxskkfbrbvgoktkcquo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5eHNra2ZicmJ2Z29rdGtjcXVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NzMyMTAsImV4cCI6MjA2OTU0OTIxMH0.U0r-cYBxGvrneLrY1RZiFAKoVJxxE0aZecFhiG7tLyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});